name: 获取请求

on:
  schedule:
    - cron: '0,30 0-16 * * *' 
  workflow_dispatch: 

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0'  

    - name: Run script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}
      run: node main.js